/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import java.io.*;
import java.sql.*;
import javax.imageio.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class AgregarVideojuego extends javax.swing.JFrame {

    /**
     * Creates new form AgregarVideojuego
     */
    public AgregarVideojuego() {
        setUndecorated(true);
        initComponents();
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        PanelPrincipal.setBackground(Color.white);
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IngresarPlataformaVideojuego = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IngresarGeneroVideojuego = new javax.swing.JComboBox<>();
        IngresarModoJuegoJuego = new javax.swing.JComboBox<>();
        IngresarAñoVideojuego = new javax.swing.JTextField();
        IngresarPrecioVideojuego = new javax.swing.JTextField();
        IngresarNombreVideojuego = new javax.swing.JTextField();
        BotonAñadir = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1585, 795));

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelPrincipal.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 730, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Agregar videojuego");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        jLabel2.setText("Nombre:");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel3.setText("Precio:");
        PanelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, -1, -1));

        jLabel4.setText("Año de lanzamiento:");
        PanelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, -1, -1));

        IngresarPlataformaVideojuego.setBackground(java.awt.Color.white);
        IngresarPlataformaVideojuego.setForeground(java.awt.Color.red);
        IngresarPlataformaVideojuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlayStation", "PC", "Nintendo" }));
        PanelPrincipal.add(IngresarPlataformaVideojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 160, 30));

        jLabel5.setText("Género:");
        PanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        jLabel6.setText("Plataforma:");
        PanelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        jLabel7.setText("Modo de juego:");
        PanelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        IngresarGeneroVideojuego.setBackground(java.awt.Color.white);
        IngresarGeneroVideojuego.setForeground(java.awt.Color.red);
        IngresarGeneroVideojuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción-Aventura", "Estrategia", "Shooter" }));
        PanelPrincipal.add(IngresarGeneroVideojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 160, 30));

        IngresarModoJuegoJuego.setBackground(java.awt.Color.white);
        IngresarModoJuegoJuego.setForeground(java.awt.Color.red);
        IngresarModoJuegoJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Un jugador", "Multijugador" }));
        PanelPrincipal.add(IngresarModoJuegoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 160, 30));

        IngresarAñoVideojuego.setBackground(java.awt.Color.white);
        IngresarAñoVideojuego.setForeground(java.awt.Color.red);
        PanelPrincipal.add(IngresarAñoVideojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 160, 30));

        IngresarPrecioVideojuego.setBackground(java.awt.Color.white);
        IngresarPrecioVideojuego.setForeground(java.awt.Color.red);
        PanelPrincipal.add(IngresarPrecioVideojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 160, 30));

        IngresarNombreVideojuego.setBackground(java.awt.Color.white);
        IngresarNombreVideojuego.setForeground(java.awt.Color.red);
        PanelPrincipal.add(IngresarNombreVideojuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 160, 30));

        BotonAñadir.setBackground(java.awt.Color.red);
        BotonAñadir.setForeground(java.awt.Color.white);
        BotonAñadir.setText("Añadir");
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAñadirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAñadirMouseExited(evt);
            }
        });
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 622, 70, 40));

        BotonVolver.setBackground(java.awt.Color.white);
        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Volver");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 622, 70, 40));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 540, 40, 50));
        PanelPrincipal.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1600, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public static BufferedImage fotoSeleccionada;
    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        // TODO add your handling code here:
        String patronPrecio = "\\d{1,3}\\.\\d{2}";
        String patronAño = "19[5-9][0-9]|20[0-4][0-9]|2050";

        nombreVideojuego = IngresarNombreVideojuego.getText();
        generoVideojuego = IngresarGeneroVideojuego.getSelectedItem().toString();
        plataformaVideojuego = IngresarPlataformaVideojuego.getSelectedItem().toString();
        modoJuego = IngresarModoJuegoJuego.getSelectedItem().toString();
        añoJuego = IngresarAñoVideojuego.getText();
        precioJuego = IngresarPrecioVideojuego.getText();

        if (IngresarNombreVideojuego.getText().isEmpty() || IngresarGeneroVideojuego.getSelectedItem().toString().isEmpty() || IngresarPlataformaVideojuego.getSelectedItem().toString().isEmpty() || IngresarModoJuegoJuego.getSelectedItem().toString().isEmpty() || IngresarAñoVideojuego.getText().isEmpty() || IngresarPrecioVideojuego.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos");
        } else if (!IngresarPrecioVideojuego.getText().matches(patronPrecio)) {
            JOptionPane.showMessageDialog(null, "El precio debe tener un formato %,__");
        } else if (!IngresarAñoVideojuego.getText().matches(patronAño)) {
            JOptionPane.showMessageDialog(null, "El año debe ser coherente");
        } else {
            JFileChooser fileChooser = new JFileChooser();
            String rutaCarpeta = "src/images/AgregarJuego";
            File carpeta = new File(rutaCarpeta);
            fileChooser.setCurrentDirectory(carpeta);
            int result = fileChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();
                urlJuego = archivoSeleccionado.getName();
                try {
                    fotoSeleccionada = ImageIO.read(archivoSeleccionado);
                } catch (IOException e) {
                    System.out.println("Error al cargar la foto: " + e.getMessage());
                }
            }

            try {
                Connection cn = conexion.Conexion.conectar();
                String consulta = "INSERT INTO videojuegos (Nombre, Género, Plataforma, `Modo de juego`, `Año de lanzamiento`, Precio, URL) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement sentencia = cn.prepareStatement(consulta);

                sentencia.setString(1, nombreVideojuego);
                sentencia.setString(2, generoVideojuego);
                sentencia.setString(3, plataformaVideojuego);
                sentencia.setString(4, modoJuego);
                sentencia.setString(5, añoJuego);
                sentencia.setString(6, precioJuego);
                sentencia.setString(7, urlJuego);
                sentencia.executeUpdate();

                JOptionPane.showMessageDialog(null, "El juego ha sido ingresado a la base de datos con éxito");
                cn.close();
                this.dispose();
                MenuPrincipalTrabajador menu = new MenuPrincipalTrabajador();

            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_BotonAñadirActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuPrincipalTrabajador menu = new MenuPrincipalTrabajador();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonAñadirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAñadirMouseEntered
        // TODO add your handling code here:
        BotonAñadir.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonAñadirMouseEntered

    private void BotonAñadirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAñadirMouseExited
        // TODO add your handling code here:
        BotonAñadir.setBackground(Color.red);
    }//GEN-LAST:event_BotonAñadirMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVideojuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTextField IngresarAñoVideojuego;
    private javax.swing.JComboBox<String> IngresarGeneroVideojuego;
    private javax.swing.JComboBox<String> IngresarModoJuegoJuego;
    private javax.swing.JTextField IngresarNombreVideojuego;
    private javax.swing.JComboBox<String> IngresarPlataformaVideojuego;
    private javax.swing.JTextField IngresarPrecioVideojuego;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
    public static String nombreVideojuego;
    public static String generoVideojuego;
    public static String plataformaVideojuego;
    public static String modoJuego;
    public static String añoJuego;
    public static String precioJuego;
    public static int ID;
    public static String urlJuego;

}
