/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;

import java.awt.geom.RoundRectangle2D;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class Filtros extends javax.swing.JFrame {

    /**
     * Creates new form Filtros
     */
    public Filtros() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        PanelFiltro.setBackground(Color.white);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        PanelFiltro = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboPlataforma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComboGenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboModoJuego = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PrecioDESC = new javax.swing.JRadioButton();
        PrecioASC = new javax.swing.JRadioButton();
        BotonVolver = new javax.swing.JButton();
        AñoDESC = new javax.swing.JRadioButton();
        AñoASC = new javax.swing.JRadioButton();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1470, 730));

        PanelFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelFiltro.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 730, 160));

        BotonBuscar.setBackground(java.awt.Color.red);
        BotonBuscar.setForeground(java.awt.Color.white);
        BotonBuscar.setText("Buscar");
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseExited(evt);
            }
        });
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        PanelFiltro.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 562, 80, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Filtros");
        PanelFiltro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        jLabel2.setText("Plataforma:");
        PanelFiltro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        ComboPlataforma.setBackground(java.awt.Color.white);
        ComboPlataforma.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboPlataforma.setForeground(java.awt.Color.red);
        ComboPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PlayStation", "PC", "Nintendo" }));
        ComboPlataforma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPlataformaActionPerformed(evt);
            }
        });
        PanelFiltro.add(ComboPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 150, -1));

        jLabel3.setText("Género:");
        PanelFiltro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        ComboGenero.setBackground(java.awt.Color.white);
        ComboGenero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboGenero.setForeground(java.awt.Color.red);
        ComboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción-Aventura", "Estrategia", "Shooter" }));
        ComboGenero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGeneroActionPerformed(evt);
            }
        });
        PanelFiltro.add(ComboGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 150, -1));

        jLabel4.setText("Año de lanzamiento:");
        PanelFiltro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, -1, -1));

        jLabel5.setText("Modo de juego:");
        PanelFiltro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        ComboModoJuego.setBackground(java.awt.Color.white);
        ComboModoJuego.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ComboModoJuego.setForeground(java.awt.Color.red);
        ComboModoJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Un jugador", "Multijugador" }));
        ComboModoJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(ComboModoJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 150, -1));

        jLabel6.setText("Precio:");
        PanelFiltro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 40, -1));

        PrecioDESC.setBackground(java.awt.Color.white);
        buttonGroup1.add(PrecioDESC);
        PrecioDESC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PrecioDESC.setForeground(java.awt.Color.red);
        PrecioDESC.setText("Mayor precio");
        PrecioDESC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(PrecioDESC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, -1, -1));

        PrecioASC.setBackground(java.awt.Color.white);
        buttonGroup1.add(PrecioASC);
        PrecioASC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PrecioASC.setForeground(java.awt.Color.red);
        PrecioASC.setText("Menor precio");
        PrecioASC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(PrecioASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, -1, -1));

        BotonVolver.setBackground(java.awt.Color.white);
        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Volver");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelFiltro.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 562, 80, 40));

        AñoDESC.setBackground(java.awt.Color.white);
        buttonGroup1.add(AñoDESC);
        AñoDESC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AñoDESC.setForeground(java.awt.Color.red);
        AñoDESC.setText("Más reciente");
        AñoDESC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(AñoDESC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, -1, -1));

        AñoASC.setBackground(java.awt.Color.white);
        buttonGroup1.add(AñoASC);
        AñoASC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AñoASC.setForeground(java.awt.Color.red);
        AñoASC.setText("Más antiguo");
        AñoASC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(AñoASC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, -1));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelFiltro.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 500, 40, 50));
        PanelFiltro.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1490, 780));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFiltro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        try {
            Connection cn = conexion.Conexion.conectar();
            String sql = "SELECT * FROM videojuegos WHERE Género = ? AND Plataforma = ? AND `Modo de juego` = ?";
            StringBuilder sqlBuilder = new StringBuilder(sql);
            ArrayList<String> valores = new ArrayList<>();

            if (AñoASC.isSelected()) {
                sqlBuilder.append(" ORDER BY `Año de lanzamiento` ASC");
            } else if (AñoDESC.isSelected()) {
                sqlBuilder.append(" ORDER BY `Año de lanzamiento` DESC");
            } else if (PrecioASC.isSelected()) {
                sqlBuilder.append(" ORDER BY Precio ASC");
            } else if (PrecioDESC.isSelected()) {
                sqlBuilder.append(" ORDER BY Precio DESC");
            }

            PreparedStatement enviarConsultas = cn.prepareStatement(sqlBuilder.toString());

            enviarConsultas.setString(1, ComboGenero.getSelectedItem().toString());
            enviarConsultas.setString(2, ComboPlataforma.getSelectedItem().toString());
            enviarConsultas.setString(3, ComboModoJuego.getSelectedItem().toString());

            ArrayList<ArrayList<String>> resultados = new ArrayList<>();

            ResultSet resultado = enviarConsultas.executeQuery();
            while (resultado.next()) {
                ArrayList<String> fila = new ArrayList<>();

                String nombre = resultado.getString("Nombre");
                String genero = resultado.getString("Género");
                String plataforma = resultado.getString("Plataforma");
                String modoJuego = resultado.getString("Modo de juego");
                String precio = resultado.getString("Precio");
                String fecha = resultado.getString("Año de lanzamiento");
                String urlImagen = resultado.getString("URL");

                fila.add(nombre);
                fila.add(genero);
                fila.add(plataforma);
                fila.add(modoJuego);

                if (RegistrarTrabajador.esTrabajador || IniciarSesionTrabajador.esTrabajador) {
                    double precioDescuento = Double.parseDouble(precio) - Double.parseDouble(precio) * 0.1;
                    DecimalFormat decimalFormat = new DecimalFormat("##.##");
                    String precioFormateado = decimalFormat.format(precioDescuento);
                    fila.add(String.valueOf(precioFormateado));
                } else if (RegistrarCliente.bandera == true || IniciarSesionCliente.cogerNombreUsu == true) {
                    fila.add(precio);
                }

                fila.add(fecha);
                fila.add(urlImagen);
                resultados.add(fila);
            }

            ArrayList<String> primerResultado = resultados.get(0);
            nombre1 = primerResultado.get(0);
            genero1 = primerResultado.get(1);
            plataforma1 = primerResultado.get(2);
            modoJuego1 = primerResultado.get(3);
            precio1 = primerResultado.get(4) + "€";
            fecha1 = primerResultado.get(5);
            urlImagen1 = primerResultado.get(6);

            ArrayList<String> segundoResultado = resultados.get(1);
            nombre2 = segundoResultado.get(0);
            genero2 = segundoResultado.get(1);
            plataforma2 = segundoResultado.get(2);
            modoJuego2 = segundoResultado.get(3);
            precio2 = segundoResultado.get(4) + "€";
            fecha2 = segundoResultado.get(5);
            urlImagen2 = segundoResultado.get(6);

            ArrayList<String> tercerResultado = resultados.get(2);
            nombre3 = tercerResultado.get(0);
            genero3 = tercerResultado.get(1);
            plataforma3 = tercerResultado.get(2);
            modoJuego3 = tercerResultado.get(3);
            precio3 = tercerResultado.get(4) + "€";
            fecha3 = tercerResultado.get(5);
            urlImagen3 = tercerResultado.get(6);

            ArrayList<String> cuartoResultado = resultados.get(3);
            nombre4 = cuartoResultado.get(0);
            genero4 = cuartoResultado.get(1);
            plataforma4 = cuartoResultado.get(2);
            modoJuego4 = cuartoResultado.get(3);
            precio4 = cuartoResultado.get(4) + "€";
            fecha4 = cuartoResultado.get(5);
            urlImagen4 = cuartoResultado.get(6);

            Resultados resul = new Resultados();
            resul.setVisible(false);

            ImageIcon icono1 = new ImageIcon("src/images/Juegos/" + urlImagen1);
            int anchoLabel = resul.Juego1.getWidth();
            int altoLabel = resul.Juego1.getHeight();
            Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);

            ImageIcon icono2 = new ImageIcon("src/images/Juegos/" + urlImagen2);
            Image imagenRedimensionada2 = icono2.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado2 = new ImageIcon(imagenRedimensionada2);

            ImageIcon icono3 = new ImageIcon("src/images/Juegos/" + urlImagen3);
            Image imagenRedimensionada3 = icono3.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado3 = new ImageIcon(imagenRedimensionada3);

            ImageIcon icono4 = new ImageIcon("src/images/Juegos/" + urlImagen4);
            Image imagenRedimensionada4 = icono4.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado4 = new ImageIcon(imagenRedimensionada4);

            resul.Juego1.setIcon(iconoRedimensionado1);
            resul.Juego2.setIcon(iconoRedimensionado2);
            resul.Juego3.setIcon(iconoRedimensionado3);
            resul.Juego4.setIcon(iconoRedimensionado4);
            cn.close();
            this.dispose();
            resul.setVisible(true);

        } catch (SQLException e) {
            System.err.println("Error al obtener los datos: " + e.getMessage());
        }

    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void ComboGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGeneroActionPerformed

    private void ComboPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPlataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPlataformaActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        if (IniciarSesionTrabajador.esTrabajador == true || RegistrarTrabajador.esTrabajador == true) {
            MenuPrincipalTrabajador menu = new MenuPrincipalTrabajador();
            this.dispose();
        } else if (IniciarSesionCliente.cogerNombreUsu == true || RegistrarCliente.bandera == true) {
            MenuPrincipalCliente menu = new MenuPrincipalCliente();
            this.dispose();
        }

    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseEntered
        // TODO add your handling code here:
        BotonBuscar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonBuscarMouseEntered

    private void BotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseExited
        // TODO add your handling code here:
        BotonBuscar.setBackground(Color.red);
    }//GEN-LAST:event_BotonBuscarMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filtros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filtros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filtros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filtros.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filtros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AñoASC;
    private javax.swing.JRadioButton AñoDESC;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JComboBox<String> ComboGenero;
    private javax.swing.JComboBox<String> ComboModoJuego;
    private javax.swing.JComboBox<String> ComboPlataforma;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelFiltro;
    private javax.swing.JRadioButton PrecioASC;
    private javax.swing.JRadioButton PrecioDESC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    public static String nombre1;
    public static String genero1;
    public static String plataforma1;
    public static String modoJuego1;
    public static String precio1;
    public static String fecha1;
    public static String urlImagen1;

    public static String nombre2;
    public static String genero2;
    public static String plataforma2;
    public static String modoJuego2;
    public static String precio2;
    public static String fecha2;
    public static String urlImagen2;

    public static String nombre3;
    public static String genero3;
    public static String plataforma3;
    public static String modoJuego3;
    public static String precio3;
    public static String fecha3;
    public static String urlImagen3;

    public static String nombre4;
    public static String genero4;
    public static String plataforma4;
    public static String modoJuego4;
    public static String precio4;
    public static String fecha4;
    public static String urlImagen4;

}
