/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.sql.*;
import java.time.*;
import javax.swing.*;

/**
 *
 * @author Hugoº
 */
public class FinalizarCompra extends javax.swing.JFrame {

    public static String nom;
    public static String dni;

    /**
     * Creates new form FinalizarCompra
     */
    public FinalizarCompra() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        PanelInicio.setBackground(Color.white);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        CheckImp.setEnabled(false);
        Check2.setEnabled(false);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 360, 360);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CorreoCompra = new javax.swing.JTextField();
        BotonHOME = new javax.swing.JButton();
        DNICompra = new javax.swing.JTextField();
        ApellidosCompra = new javax.swing.JTextField();
        NombreCompra = new javax.swing.JTextField();
        BotonComprobar = new javax.swing.JButton();
        CheckImp = new javax.swing.JCheckBox();
        Check2 = new javax.swing.JCheckBox();
        BotonFinalizarCompra = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        BancoCompra = new javax.swing.JTextField();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1790, 1025));

        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelInicio.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 790, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Compra");
        PanelInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, -1, -1));

        jLabel2.setText("Nombre:");
        PanelInicio.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        jLabel3.setText("Apellidos:");
        PanelInicio.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        jLabel4.setText("DNI:");
        PanelInicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        jLabel5.setText("Correo electrónico:");
        PanelInicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, -1, -1));

        jLabel6.setText("Cuenta bancaria:");
        PanelInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        CorreoCompra.setForeground(java.awt.Color.red);
        PanelInicio.add(CorreoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 680, 290, -1));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 700, 70, 70));

        DNICompra.setForeground(java.awt.Color.red);
        PanelInicio.add(DNICompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 560, 370, -1));

        ApellidosCompra.setForeground(java.awt.Color.red);
        PanelInicio.add(ApellidosCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 340, -1));

        NombreCompra.setForeground(java.awt.Color.red);
        PanelInicio.add(NombreCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 350, -1));

        BotonComprobar.setBackground(java.awt.Color.red);
        BotonComprobar.setForeground(java.awt.Color.white);
        BotonComprobar.setText("Comprobar datos");
        BotonComprobar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonComprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonComprobarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonComprobarMouseExited(evt);
            }
        });
        BotonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprobarActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, 150, 50));

        CheckImp.setBackground(java.awt.Color.white);
        CheckImp.setText("Acepto todos los términos y condiciones");
        CheckImp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckImpActionPerformed(evt);
            }
        });
        PanelInicio.add(CheckImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 760, 350, -1));

        Check2.setBackground(java.awt.Color.white);
        Check2.setText("Quiero recibir información sobre futuras ofertas y novedades");
        Check2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Check2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check2ActionPerformed(evt);
            }
        });
        PanelInicio.add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 790, -1, -1));

        BotonFinalizarCompra.setBackground(java.awt.Color.red);
        BotonFinalizarCompra.setForeground(java.awt.Color.white);
        BotonFinalizarCompra.setText("Finalizar compra");
        BotonFinalizarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFinalizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonFinalizarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonFinalizarCompraMouseExited(evt);
            }
        });
        BotonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFinalizarCompraActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonFinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 840, 150, 40));

        BotonCancelar.setBackground(java.awt.Color.white);
        BotonCancelar.setForeground(java.awt.Color.red);
        BotonCancelar.setText("Cancelar");
        BotonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseExited(evt);
            }
        });
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 850, 100, 30));

        BancoCompra.setForeground(java.awt.Color.red);
        PanelInicio.add(BancoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 300, -1));
        PanelInicio.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 1810, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckImpActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_CheckImpActionPerformed

    private void BotonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFinalizarCompraActionPerformed
        // TODO add your handling code here:

        nombreComprador = NombreCompra.getText();
        apellidosComprador = ApellidosCompra.getText();
        dniComprador = DNICompra.getText();
        cuentaComprador = BancoCompra.getText();
        correoCompra = CorreoCompra.getText();

        if (CheckImp.isSelected()) {

            if (NombreCompra.getText().isEmpty() || DNICompra.getText().isEmpty() || ApellidosCompra.getText().isEmpty() || BancoCompra.getText().isEmpty() || CorreoCompra.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos antes de completar la compra", "Escribe los datos", JOptionPane.WARNING_MESSAGE);
            } else {
                fecha = java.time.LocalDate.now();

                if (IniciarSesionCliente.cogerNombreUsu == true || RegistrarCliente.bandera == true) {
                    try {
                        Connection cn = conexion.Conexion.conectar();

                        String enviarConsulta = "INSERT INTO compras (NombreComprador, ApellidosComprador, DNIComprador, CuentaBancaria, CorreoCompra, ID_CLIENTES, ID_VIDEOJUEGOS) VALUES (?, ?, ?, ?, ?, ?, ?) ";

                        PreparedStatement sentencia = cn.prepareStatement(enviarConsulta);

                        sentencia.setString(1, nombreComprador);
                        sentencia.setString(2, apellidosComprador);
                        sentencia.setString(3, dniComprador);
                        sentencia.setString(4, cuentaComprador);
                        sentencia.setString(5, correoCompra);
                        if (RegistrarCliente.bandera == true) {
                            sentencia.setInt(6, RegistrarCliente.ID);
                        } else {
                            sentencia.setInt(6, IniciarSesionCliente.ID);
                        }
                        sentencia.setInt(7, Resultados.ID);

                        sentencia.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Su pedido ha sido realizado, recibirá un email de confirmación en su correo electrónico.");
                        this.dispose();
                        DatosCompra datos = new DatosCompra();
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                } else if (IniciarSesionTrabajador.esTrabajador == true || RegistrarTrabajador.bandera == true) {
                    try {
                        Connection cn = conexion.Conexion.conectar();

                        String enviarConsulta = "INSERT INTO compras (NombreComprador, ApellidosComprador, DNIComprador, CuentaBancaria, CorreoCompra, ID_TRABAJADORES, ID_VIDEOJUEGOS) VALUES (?, ?, ?, ?, ?, ?, ?) ";

                        PreparedStatement sentencia = cn.prepareStatement(enviarConsulta);

                        sentencia.setString(1, nombreComprador);
                        sentencia.setString(2, apellidosComprador);
                        sentencia.setString(3, dniComprador);
                        sentencia.setString(4, cuentaComprador);
                        sentencia.setString(5, correoCompra);
                        if (RegistrarTrabajador.bandera == true) {
                            sentencia.setInt(6, RegistrarTrabajador.ID);
                        } else {
                            sentencia.setInt(6, IniciarSesionTrabajador.ID);
                        }
                        sentencia.setInt(7, Resultados.ID);

                        sentencia.executeUpdate();

                        JOptionPane.showMessageDialog(null, "Su pedido ha sido realizado, recibirá un email de confirmación en su correo electrónico.");
                        cn.close();
                        this.dispose();
                        DatosCompra datos = new DatosCompra();

                    } catch (SQLException e) {
                        e.printStackTrace();
                    }

                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes aceptar la política de terminos y condiciones");
        }


    }//GEN-LAST:event_BotonFinalizarCompraActionPerformed

    private void Check2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Check2ActionPerformed

    private void BotonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprobarActionPerformed
        // TODO add your handling code here:
        String patronDNI = "\\d{8}[A-HJ-NP-TV-Z]";
        String patronNoNums = "[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+";
        String patronCuentaIBAN = "^([A-Z]{2})(\\d{18})$";
        String patronEmail = "^.+@.+\\..+$";

        if (NombreCompra.getText().isEmpty() || DNICompra.getText().isEmpty() || ApellidosCompra.getText().isEmpty() || BancoCompra.getText().isEmpty() || CorreoCompra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos", "Rellena", JOptionPane.WARNING_MESSAGE);
        } else if (!DNICompra.getText().matches(patronDNI)) {
            JOptionPane.showMessageDialog(null, "Debes introducir un DNI válido");
        } else if (!NombreCompra.getText().matches(patronNoNums)) {
            JOptionPane.showMessageDialog(null, "Debes introducir un nombre sin números");
        } else if (!ApellidosCompra.getText().matches(patronNoNums)) {
            JOptionPane.showMessageDialog(null, "Debes introducir apellidos sin números");
        } else if (!BancoCompra.getText().matches(patronCuentaIBAN)) {
            JOptionPane.showMessageDialog(null, "Debes introducir un IBAN válido");
        } else if (!CorreoCompra.getText().matches(patronEmail)) {
            JOptionPane.showMessageDialog(null, "Debes introducir un código postal válido");
        } else {
            JOptionPane.showMessageDialog(null, "Los datos son válidos");
            CheckImp.setEnabled(true);
            Check2.setEnabled(true);
        }
    }//GEN-LAST:event_BotonComprobarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Filtros filtros = new Filtros();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText(" X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonComprobarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComprobarMouseEntered
        // TODO add your handling code here:
        BotonComprobar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonComprobarMouseEntered

    private void BotonComprobarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComprobarMouseExited
        // TODO add your handling code here:
        BotonComprobar.setBackground(Color.red);
    }//GEN-LAST:event_BotonComprobarMouseExited

    private void BotonFinalizarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFinalizarCompraMouseEntered
        // TODO add your handling code here:
        BotonFinalizarCompra.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonFinalizarCompraMouseEntered

    private void BotonFinalizarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFinalizarCompraMouseExited
        // TODO add your handling code here:
        BotonFinalizarCompra.setBackground(Color.red);
    }//GEN-LAST:event_BotonFinalizarCompraMouseExited

    private void BotonCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseEntered
        // TODO add your handling code here:
        BotonCancelar.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonCancelarMouseEntered

    private void BotonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseExited
        // TODO add your handling code here:
        BotonCancelar.setBackground(Color.white);
    }//GEN-LAST:event_BotonCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField ApellidosCompra;
    public static javax.swing.JTextField BancoCompra;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonComprobar;
    private javax.swing.JButton BotonFinalizarCompra;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox CheckImp;
    public static javax.swing.JTextField CorreoCompra;
    public static javax.swing.JTextField DNICompra;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    public static javax.swing.JTextField NombreCompra;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
     public static String nombreComprador;
    public static String apellidosComprador;
    public static String dniComprador;
    public static String cuentaComprador;
    public static String correoCompra;
    public static LocalDate fecha;
}
