/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio3
     */
    public Inicio() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        BotonRegistrar.setBackground(Color.red);
        BotonSesion.setBackground(Color.red);
        setIconImage(getIconImage());

      
        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);
        
        setVisible(true);

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonHOME = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();
        BotonSesion = new javax.swing.JButton();
        BotonRegistrar = new javax.swing.JButton();
        LabelPeqDesc1 = new javax.swing.JLabel();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1405, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(null);
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        jPanel1.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 350, 40, 50));
        jPanel1.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 790, 150));

        BotonSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonSesion.setForeground(java.awt.Color.white);
        BotonSesion.setText("Iniciar Sesión");
        BotonSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSesionMouseExited(evt);
            }
        });
        BotonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSesionActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 140, 40));

        BotonRegistrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonRegistrar.setForeground(java.awt.Color.white);
        BotonRegistrar.setText("Registrar");
        BotonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarMouseExited(evt);
            }
        });
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 130, 40));

        LabelPeqDesc1.setBackground(java.awt.Color.white);
        LabelPeqDesc1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelPeqDesc1.setForeground(java.awt.Color.black);
        LabelPeqDesc1.setText("Tu tienda de videojuegos de confianza");
        jPanel1.add(LabelPeqDesc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, 40));
        jPanel1.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1440, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSesionActionPerformed
        // TODO add your handling code here:
        String[] opciones = {"Cliente", "Trabajador"};
        int puntuacion = JOptionPane.showOptionDialog(null, "¿Desea acceder como cliente o como trabajador?", "Confirme", JOptionPane.INFORMATION_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if (puntuacion == 0) {
            IniciarSesionCliente iniciar = new IniciarSesionCliente();
            this.dispose();
        } else if (puntuacion == 1) {
            IniciarSesionTrabajador iniciar2 = new IniciarSesionTrabajador();
            this.dispose();
        }
    }//GEN-LAST:event_BotonSesionActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
         String[] opciones = {"Cliente", "Trabajador"};
        int puntuacion = JOptionPane.showOptionDialog(null, "¿Desea registrarse como cliente o como trabajador?", "Confirme", JOptionPane.INFORMATION_MESSAGE, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        if (puntuacion == 0) {
            RegistrarCliente registro = new RegistrarCliente();
            this.dispose();
        } else if (puntuacion == 1) {
            RegistrarTrabajador registrar = new RegistrarTrabajador();
            this.dispose();
        }
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText(" X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseEntered
        // TODO add your handling code here:
         BotonRegistrar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonRegistrarMouseEntered

    private void BotonRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarMouseExited
        // TODO add your handling code here:
        BotonRegistrar.setBackground(Color.red);
    }//GEN-LAST:event_BotonRegistrarMouseExited

    private void BotonSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesionMouseEntered
        // TODO add your handling code here:
        BotonSesion.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonSesionMouseEntered

    private void BotonSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSesionMouseExited
        // TODO add your handling code here:
        BotonSesion.setBackground(Color.red);
    }//GEN-LAST:event_BotonSesionMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonSesion;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelPeqDesc1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
