/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class Inicio_1 extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio_1() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        PanelInicio.setBackground(Color.white);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        LabelLogo.setIcon(imagen);
        BotonAcceder.setBackground(Color.red);
        BotonCerrarSesion.setBackground(Color.red);
        setIconImage(getIconImage());
        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");

        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new javax.swing.JPanel();
        BotonHOME = new javax.swing.JButton();
        BotonCerrarSesion = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();
        LabelPeqDesc = new javax.swing.JLabel();
        BotonAcceder = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1480, 520));

        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 350, 40, 50));

        BotonCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonCerrarSesion.setForeground(java.awt.Color.white);
        BotonCerrarSesion.setText("Cerrar sesión");
        BotonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCerrarSesionMouseExited(evt);
            }
        });
        BotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 140, 40));
        PanelInicio.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 790, 160));

        LabelPeqDesc.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LabelPeqDesc.setForeground(java.awt.Color.black);
        LabelPeqDesc.setText("Tu tienda de videojuegos de confianza");
        PanelInicio.add(LabelPeqDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));

        BotonAcceder.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonAcceder.setForeground(java.awt.Color.white);
        BotonAcceder.setText("Acceder");
        BotonAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAccederMouseExited(evt);
            }
        });
        BotonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccederActionPerformed(evt);
            }
        });
        PanelInicio.add(BotonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 140, 40));

        LabelFondo.setBackground(java.awt.Color.white);
        PanelInicio.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1500, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BotonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionActionPerformed
        // TODO add your handling code here:

        int cerrar = JOptionPane.showConfirmDialog(null, "¿Estás seguro?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (cerrar == 0) {
            this.dispose();
            Inicio inicio = new Inicio();
        } else {

        }


    }//GEN-LAST:event_BotonCerrarSesionActionPerformed

    private void BotonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccederActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (RegistrarCliente.bandera == true) {
            MenuPrincipalCliente menu = new MenuPrincipalCliente();
        } else if (RegistrarTrabajador.esTrabajador == true) {
            MenuPrincipalTrabajador menu2 = new MenuPrincipalTrabajador();
        }
    }//GEN-LAST:event_BotonAccederActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText(" X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarSesionMouseExited
        // TODO add your handling code here:
        BotonCerrarSesion.setBackground(Color.red);
    }//GEN-LAST:event_BotonCerrarSesionMouseExited

    private void BotonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarSesionMouseEntered
        // TODO add your handling code here:
        BotonCerrarSesion.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonCerrarSesionMouseEntered

    private void BotonAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAccederMouseEntered
        // TODO add your handling code here:
         BotonAcceder.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonAccederMouseEntered

    private void BotonAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAccederMouseExited
        // TODO add your handling code here:
       BotonAcceder.setBackground(Color.red);
    }//GEN-LAST:event_BotonAccederMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAcceder;
    private javax.swing.JButton BotonCerrarSesion;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel LabelPeqDesc;
    private javax.swing.JPanel PanelInicio;
    // End of variables declaration//GEN-END:variables
}
