/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class MenuPrincipalCliente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalCliente() {
        setUndecorated(true);
        initComponents();
        Cliente cliente = new Cliente();
        setLocationRelativeTo(null);
        setResizable(false);

        if (IniciarSesionCliente.cogerNombreUsu == true) {
            InsertarNombre.setText(IniciarSesionCliente.nombreUsuario);
        } else if (IniciarSesionCliente.cogerNombreUsu == false) {
            InsertarNombre.setText(RegistrarCliente.nombreUsuario);

        }

        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        PanelMenu.setBackground(Color.white);
        BotonRealizarCompra.setBackground(Color.red);
        BotonVerRegistro.setBackground(Color.red);
        BotonSalir.setBackground(Color.white);
        setIconImage(getIconImage());
        
          ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);
        
        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMenu = new javax.swing.JPanel();
        InsertarNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonRealizarCompra = new javax.swing.JButton();
        BotonVerRegistro = new javax.swing.JButton();
        LabelLogo = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        BotonCerrarSesion = new javax.swing.JButton();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1470, 670));

        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertarNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PanelMenu.add(InsertarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 330, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Bienvenido ");
        PanelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("¿Qué desea hacer?");
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        BotonRealizarCompra.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonRealizarCompra.setForeground(java.awt.Color.white);
        BotonRealizarCompra.setText("Realizar compra");
        BotonRealizarCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonRealizarCompra.setBorderPainted(false);
        BotonRealizarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRealizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRealizarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRealizarCompraMouseExited(evt);
            }
        });
        BotonRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRealizarCompraActionPerformed(evt);
            }
        });
        PanelMenu.add(BotonRealizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 410, 50));

        BotonVerRegistro.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonVerRegistro.setForeground(java.awt.Color.white);
        BotonVerRegistro.setText("Ver registro");
        BotonVerRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonVerRegistro.setBorderPainted(false);
        BotonVerRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVerRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVerRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVerRegistroMouseExited(evt);
            }
        });
        BotonVerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerRegistroActionPerformed(evt);
            }
        });
        PanelMenu.add(BotonVerRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 410, 50));
        PanelMenu.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 730, 160));

        BotonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonSalir.setForeground(java.awt.Color.red);
        BotonSalir.setText("Salir");
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        PanelMenu.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 140, 40));

        BotonCerrarSesion.setBackground(java.awt.Color.white);
        BotonCerrarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonCerrarSesion.setForeground(java.awt.Color.red);
        BotonCerrarSesion.setText("Cerrar sesión");
        BotonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCerrarSesionMouseExited(evt);
            }
        });
        BotonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCerrarSesionActionPerformed(evt);
            }
        });
        PanelMenu.add(BotonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 140, 40));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelMenu.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 460, 40, 50));
        PanelMenu.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1510, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRealizarCompraActionPerformed
        // TODO add your handling code here:
        Filtros filtro = new Filtros();
        this.dispose();
    }//GEN-LAST:event_BotonRealizarCompraActionPerformed

    private void BotonVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerRegistroActionPerformed
        // TODO add your handling code here:
        Registro registro = new Registro();
        this.dispose();
    }//GEN-LAST:event_BotonVerRegistroActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea salir de la tienda?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCerrarSesionActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de querer cerrar sesión?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            this.dispose();
            Inicio incio = new Inicio();
        }

    }//GEN-LAST:event_BotonCerrarSesionActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonRealizarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRealizarCompraMouseEntered
        // TODO add your handling code here:
        BotonRealizarCompra.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonRealizarCompraMouseEntered

    private void BotonRealizarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRealizarCompraMouseExited
        // TODO add your handling code here:
        BotonRealizarCompra.setBackground(Color.red);
    }//GEN-LAST:event_BotonRealizarCompraMouseExited

    private void BotonVerRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerRegistroMouseEntered
        // TODO add your handling code here:
        BotonVerRegistro.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonVerRegistroMouseEntered

    private void BotonVerRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerRegistroMouseExited
        // TODO add your handling code here:
        BotonVerRegistro.setBackground(Color.red);
    }//GEN-LAST:event_BotonVerRegistroMouseExited

    private void BotonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarSesionMouseEntered
        // TODO add your handling code here:
        BotonCerrarSesion.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonCerrarSesionMouseEntered

    private void BotonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarSesionMouseExited
        // TODO add your handling code here:
        BotonCerrarSesion.setBackground(Color.white);
    }//GEN-LAST:event_BotonCerrarSesionMouseExited

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        // TODO add your handling code here:
        BotonSalir.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        // TODO add your handling code here:
        BotonSalir.setBackground(Color.white);
    }//GEN-LAST:event_BotonSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrarSesion;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonRealizarCompra;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonVerRegistro;
    public static javax.swing.JLabel InsertarNombre;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
