/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        PanelDatos.setBackground(Color.white);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        BotonBuscar.setBackground(Color.red);
        BotonVolver.setBackground(Color.white);
        PanelPocosDatos.setBackground(Color.red);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        BotonVolver = new javax.swing.JButton();
        PanelPocosDatos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BuscarNombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuscarDNI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BuscarContacto = new javax.swing.JLabel();
        BotonVerMas = new javax.swing.JButton();
        LabelImagen = new javax.swing.JLabel();
        PanelCliente = new javax.swing.JLabel();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1560, 770));

        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelDatos.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 720, 160));

        jLabel1.setText("DNI:");
        PanelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        dni.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PanelDatos.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 160, -1));

        BotonBuscar.setForeground(java.awt.Color.white);
        BotonBuscar.setText("Buscar");
        BotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseExited(evt);
            }
        });
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 90, -1));

        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Volver");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 640, 90, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Nombre:");

        BuscarNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BuscarNombre.setForeground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");

        BuscarDNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BuscarDNI.setForeground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Contacto:");

        BuscarContacto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BuscarContacto.setForeground(java.awt.Color.white);

        BotonVerMas.setBackground(java.awt.Color.white);
        BotonVerMas.setText("Ver más");
        BotonVerMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVerMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVerMasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVerMasMouseExited(evt);
            }
        });
        BotonVerMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerMasActionPerformed(evt);
            }
        });

        LabelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelPocosDatosLayout = new javax.swing.GroupLayout(PanelPocosDatos);
        PanelPocosDatos.setLayout(PanelPocosDatosLayout);
        PanelPocosDatosLayout.setHorizontalGroup(
            PanelPocosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPocosDatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelPocosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BuscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(BuscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPocosDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonVerMas)
                .addGap(70, 70, 70))
        );
        PanelPocosDatosLayout.setVerticalGroup(
            PanelPocosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPocosDatosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelPocosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPocosDatosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonVerMas)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PanelDatos.add(PanelPocosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 400, 260));

        PanelCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelCliente.setText("Datos cliente/trabajador");
        PanelDatos.add(PanelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 280, -1));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 530, 40, 50));
        PanelDatos.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1580, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        if (IniciarSesionTrabajador.esTrabajador == true || RegistrarTrabajador.esTrabajador == true) {
            MenuPrincipalTrabajador menu = new MenuPrincipalTrabajador();
            this.dispose();
        } else if (IniciarSesionCliente.cogerNombreUsu == true || RegistrarCliente.bandera == true) {
            MenuPrincipalCliente menu = new MenuPrincipalCliente();
            this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed
    }
    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        if (dni.getText().isEmpty()) {
            dni.setText("");
            BuscarNombre.setText("");
            BuscarDNI.setText("");
            BuscarContacto.setText("");
            LabelImagen.setIcon(vacio);
            JOptionPane.showMessageDialog(null, "Debes introducir el DNI primero");
        } else
            try {
            Connection cn = conexion.Conexion.conectar();
            String sql = "SELECT * FROM clientes WHERE DNI = ?";
            PreparedStatement enviarConsultas = cn.prepareStatement(sql);
            enviarConsultas.setString(1, dni.getText());
            ResultSet resultado = enviarConsultas.executeQuery();

            if (resultado.next()) {

                nombre = resultado.getString("Nombre");
                apellidos = resultado.getString("Apellidos");
                DNI = resultado.getString("DNI");
                contacto = resultado.getString("Contacto");
                ciudad = resultado.getString("Ciudad");
                cp = resultado.getString("CodigoPostal");
                pais = String.valueOf(resultado.getString("Pais"));
                urlImage = resultado.getString("URL");
                clienteTrabajador = true;
            }

            String sql2 = "SELECT * FROM trabajadores WHERE DNI = ?";
            PreparedStatement enviarConsultas2 = cn.prepareStatement(sql2);
            enviarConsultas2.setString(1, dni.getText());
            ResultSet resultado2 = enviarConsultas2.executeQuery();

            if (resultado2.next()) {

                nombre = resultado2.getString("Nombre");
                apellidos = resultado2.getString("Apellidos");
                DNI = resultado2.getString("DNI");
                pais = String.valueOf(resultado2.getString("Pais"));
                ciudad = resultado2.getString("Ciudad");
                contacto = resultado2.getString("Contacto");
                urlImage = resultado2.getString("URL");
                puesto = resultado2.getString("Puesto");
                clienteTrabajador = false;
            }

            if (!dni.getText().equals(DNI)) {
                dni.setText("");
                BuscarNombre.setText("");
                BuscarDNI.setText("");
                BuscarContacto.setText("");
                LabelImagen.setIcon(vacio);
                JOptionPane.showMessageDialog(null, "Debes introducir un DNI válido");
            } else {
                bandera = true;

                BuscarNombre.setText(nombre + " " + apellidos + "\n");
                BuscarDNI.setText(DNI + "\n");
                BuscarContacto.setText(contacto + "\n");

                ImageIcon icono = new ImageIcon("src/images/Personas/" + urlImage);
                int anchoLabel = LabelImagen.getWidth();
                int altoLabel = LabelImagen.getHeight();
                Image imagenRedimensionada = icono.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
                ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);

                LabelImagen.setIcon(iconoRedimensionado);
            }
            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener los datos" + e.getMessage());

        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonVerMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerMasActionPerformed
        // TODO add your handling code here:

        if (dni.getText().isEmpty() || bandera == false) {
            JOptionPane.showMessageDialog(null, "Debes introducir un DNI");
        } else if (!dni.getText().equals(DNI) || bandera == false) {
            JOptionPane.showMessageDialog(null, "Debes introducir un DNI válido");
        } else {
            this.dispose();
            TodosDatos datos = new TodosDatos();
            ImageIcon icono = new ImageIcon("src/images/Personas/" + urlImage);
            int anchoLabel = datos.ValorFoto.getWidth();
            int altoLabel = datos.ValorFoto.getHeight();
            Image imagenRedimensionada2 = icono.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado2 = new ImageIcon(imagenRedimensionada2);

            datos.ValorNombre.setText(nombre);
            datos.ValorApellidos.setText(apellidos);
            datos.ValorDNI.setText(DNI);
            datos.ValorContacto.setText(contacto);
            datos.ValorCiudad.setText(ciudad + ", " + pais);
            if (clienteTrabajador == true) {
                datos.PuestoLabel.setVisible(false);
                datos.ValorPuesto.setText(cp);
            } else {
                datos.CPLabel.setVisible(false);
                datos.ValorPuesto.setText(puesto);
            }
            datos.ValorFoto.setIcon(iconoRedimensionado2);
            LabelImagen.setIcon(vacio);
        }

    }//GEN-LAST:event_BotonVerMasActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseEntered
        // TODO add your handling code here:
        BotonBuscar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonBuscarMouseEntered

    private void BotonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseExited
        // TODO add your handling code here:
        BotonBuscar.setBackground(Color.red);
    }//GEN-LAST:event_BotonBuscarMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    private void BotonVerMasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerMasMouseEntered
        // TODO add your handling code here:
        BotonVerMas.setBackground(new Color(255, 102, 102));
        BotonVerMas.setForeground(Color.white);
    }//GEN-LAST:event_BotonVerMasMouseEntered

    private void BotonVerMasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerMasMouseExited
        // TODO add your handling code here:
        BotonVerMas.setBackground(Color.white);
         BotonVerMas.setForeground(Color.black);
    }//GEN-LAST:event_BotonVerMasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonVerMas;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel BuscarContacto;
    private javax.swing.JLabel BuscarDNI;
    private javax.swing.JLabel BuscarNombre;
    private javax.swing.JLabel LabelFondo;
    public static javax.swing.JLabel LabelImagen;
    private javax.swing.JLabel LabelLogo;
    public static javax.swing.JLabel PanelCliente;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelPocosDatos;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    public static String nombre;
    public static String apellidos;
    public static String DNI;
    public static String contacto;
    public static String nombre2;
    public static String apellidos2;
    public static String contacto2;
    public static String pais;
    public static String cp;
    public static String ciudad;
    public static String urlImage;
    public static String pais2;
    public static String ciudad2;
    public static String urlImage2;
    public static String puesto;

    public static ImageIcon iconoRedimensionado;
    public boolean bandera;
    public ImageIcon vacio;
    public static boolean clienteTrabajador;

}
