/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.*;
import java.io.*;
import java.sql.*;
import javax.imageio.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        setLocationRelativeTo(null);
        setResizable(false);

        PanelRegistro.setBackground(Color.white);
        RellenarPais.setBackground(Color.white);
        BotonRegistro.setBackground(Color.red);
        BotonVolver.setBackground(Color.white);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);

    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RellenarApellidos = new javax.swing.JTextField();
        RellenarDNI = new javax.swing.JTextField();
        RellenarTelefono = new javax.swing.JTextField();
        RellenarNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BotonRegistro = new javax.swing.JButton();
        RellenarPais = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RellenarCiudad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        RellenarCP = new javax.swing.JTextField();
        LabelLogo = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1445, 725));
        setResizable(false);

        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Rellene los datos para registrarse");
        PanelRegistro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 390, 52));

        jLabel2.setText("Nombre:");
        PanelRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jLabel3.setText("Apellidos:");
        PanelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel4.setText("DNI:");
        PanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        jLabel5.setText("País:");
        PanelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));
        PanelRegistro.add(RellenarApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 160, -1));

        RellenarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenarDNIActionPerformed(evt);
            }
        });
        PanelRegistro.add(RellenarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 160, -1));
        PanelRegistro.add(RellenarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, 160, -1));

        RellenarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenarNombreActionPerformed(evt);
            }
        });
        PanelRegistro.add(RellenarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 160, -1));

        jLabel6.setText("Contacto:");
        PanelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, -1, -1));

        BotonRegistro.setForeground(java.awt.Color.white);
        BotonRegistro.setText("Registrar");
        BotonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistroMouseExited(evt);
            }
        });
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        PanelRegistro.add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 90, 40));

        RellenarPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "España", "Inglaterra", "Alemania", "Francia" }));
        RellenarPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RellenarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenarPaisActionPerformed(evt);
            }
        });
        PanelRegistro.add(RellenarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 160, 30));

        jLabel7.setText("Código postal:");
        PanelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));
        PanelRegistro.add(RellenarCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 160, -1));

        jLabel8.setText("Ciudad:");
        PanelRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));
        PanelRegistro.add(RellenarCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 160, -1));
        PanelRegistro.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 710, 140));

        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Volver");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelRegistro.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 70, 30));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelRegistro.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 490, 40, 50));
        PanelRegistro.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 1470, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimirFoto(File file) {

        try {
            BufferedImage image = ImageIO.read(file);

            System.out.println("Imprimiendo foto: " + file.getName());
        } catch (IOException e) {
            System.out.println("Error al cargar la foto: " + e.getMessage());
        }
    }
    public static BufferedImage fotoSeleccionada;

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        // TODO add your handling code here:  
        String patronDNI = "\\d{8}[A-HJ-NP-TV-Z]";
        String patronCP = "\\d+";
        String patronNoNums = "[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+";
        Cliente cliente = new Cliente();

        Connection cn = conexion.Conexion.conectar();
        // Verificar si el DNI ya existe en la base de datos
        String consul1 = "SELECT DNI FROM clientes WHERE DNI = ?";

        try (PreparedStatement statement = cn.prepareStatement(consul1)) {
            statement.setString(1, RellenarDNI.getText());
            ResultSet resultSet = statement.executeQuery();

            if (resultSet.next()) {
                comprobardni = resultSet.getString(1);
            } else {
                comprobardni = null; 
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        String consul2 = "SELECT DNI FROM trabajadores WHERE DNI = ?";

        try (PreparedStatement statement2 = cn.prepareStatement(consul2)) {
            statement2.setString(1, RellenarDNI.getText());
            ResultSet resultSet2 = statement2.executeQuery();

            if (resultSet2.next()) {
                comprobardni2 = resultSet2.getString(1);
            } else {
                comprobardni2 = null; 
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        if (comprobardni != null && comprobardni.equals(RellenarDNI.getText())) {
            cliente.comprobarDNI();
        } else if (comprobardni2 != null && comprobardni2.equals(RellenarDNI.getText())) {
            cliente.comprobarDNI2();
        }else if (RellenarNombre.getText().isEmpty() || RellenarApellidos.getText().isEmpty() || RellenarDNI.getText().isEmpty() || RellenarCiudad.getText().isEmpty() || RellenarCP.getText().isEmpty() || RellenarTelefono.getText().isEmpty()) {
            cliente.comprobarCamposVacios();

        } else if (!RellenarDNI.getText().matches(patronDNI)) {
            cliente.comprobarCampos();
        } else if (!RellenarNombre.getText().matches(patronNoNums)) {
            cliente.comprobarNombre();
        } else if (!RellenarApellidos.getText().matches(patronNoNums)) {
            cliente.comprobarApellidos();
        } else if (!RellenarTelefono.getText().matches(patronCP) || RellenarTelefono.getText().length() != 9) {
            cliente.comprobarContacto();
        } else if (!RellenarCP.getText().matches(patronCP) || RellenarCP.getText().length() != 5) {
            cliente.comprobarCP();
        } else if (!RellenarCiudad.getText().matches(patronNoNums)) {
            cliente.comprobarCiudad();
        } else {

            cliente.setNombre(RellenarNombre.getText());
            cliente.setApellidos(RellenarApellidos.getText());
            cliente.setDNI(RellenarDNI.getText());
            cliente.setPais(RellenarPais.getSelectedItem().toString());
            cliente.setCiudad(RellenarCiudad.getText());
            cliente.setCodigoPostal(RellenarCP.getText());
            cliente.setContacto(RellenarTelefono.getText());

            nombreUsuario = JOptionPane.showInputDialog(null, "Ahora introduzca su nombre de usuario");
            cliente.setNombreUsuario(nombreUsuario);

            while (cliente.getNombreUsuario().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No puedes dejar el campo vacío", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                cliente.setNombreUsuario(JOptionPane.showInputDialog(null, "Ahora introduzca su nombre de usuario"));
            }

            cliente.setContraseña(JOptionPane.showInputDialog(null, "Ahora introduzca una contraseña"));
            while (cliente.getNombreUsuario().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No puedes dejar el campo vacío", "Campo vacío", JOptionPane.ERROR_MESSAGE);
                cliente.setContraseña(JOptionPane.showInputDialog(null, "Ahora introduzca una contraseña"));
            }

            JOptionPane.showMessageDialog(null, "Por último introduzca una foto");

            JFileChooser fileChooser = new JFileChooser();
            String rutaCarpeta = "src/images/Personas";
            File carpeta = new File(rutaCarpeta);
            fileChooser.setCurrentDirectory(carpeta);
            int result = fileChooser.showOpenDialog(null);
            if (result == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();
                urlImagen = archivoSeleccionado.getName();
                try {
                    fotoSeleccionada = ImageIO.read(archivoSeleccionado);
                } catch (IOException e) {
                    System.out.println("Error al cargar la foto: " + e.getMessage());
                }
            }

            try {

                String consulta = "INSERT INTO clientes (Nombre, Apellidos, DNI, Pais, Ciudad, CodigoPostal, Contacto, URL, NombreUsuario, Contraseña) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement sentencia = cn.prepareStatement(consulta, Statement.RETURN_GENERATED_KEYS);

                sentencia.setString(1, cliente.getNombre());
                sentencia.setString(2, cliente.getApellidos());
                sentencia.setString(3, cliente.getDNI());
                sentencia.setString(4, cliente.getPais());
                sentencia.setString(5, cliente.getCiudad());
                sentencia.setString(6, cliente.getCodigoPostal());
                sentencia.setString(7, cliente.getContacto());
                sentencia.setString(8, urlImagen);
                sentencia.setString(9, nombreUsuario);
                sentencia.setString(10, cliente.getContraseña());

                int obtenerId = sentencia.executeUpdate();

                if (obtenerId > 0) {
                    ResultSet clavePrimaria = sentencia.getGeneratedKeys();
                    if (clavePrimaria.next()) {
                        ID = clavePrimaria.getInt(1);
                    }
                }

                bandera = true;
                Inicio_1 inicio = new Inicio_1();
                cn.close();
                this.dispose();

            } catch (SQLException e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void RellenarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenarNombreActionPerformed
        // TODO add your handling code here

    }//GEN-LAST:event_RellenarNombreActionPerformed

    private void RellenarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenarPaisActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RellenarPaisActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Inicio inicio = new Inicio();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void RellenarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RellenarDNIActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistroMouseEntered
        // TODO add your handling code here:
        BotonRegistro.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonRegistroMouseEntered

    private void BotonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistroMouseExited
        // TODO add your handling code here:
        BotonRegistro.setBackground(Color.red);
    }//GEN-LAST:event_BotonRegistroMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JTextField RellenarApellidos;
    private javax.swing.JTextField RellenarCP;
    private javax.swing.JTextField RellenarCiudad;
    private javax.swing.JTextField RellenarDNI;
    public static javax.swing.JTextField RellenarNombre;
    private javax.swing.JComboBox<String> RellenarPais;
    private javax.swing.JTextField RellenarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
    public static int ID;
    String urlImagen;
    public static boolean bandera = false;
    public static String nombreUsuario;
    public static String dni;
    public static String comprobardni;
    public static String comprobardni2;
}
