/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Filtros
     */
    public Resultados() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        PanelFiltros.setBackground(Color.white);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 500, 500);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFiltros = new javax.swing.JPanel();
        BotonHOME = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LabelLogo = new javax.swing.JLabel();
        Juego4 = new javax.swing.JButton();
        Juego1 = new javax.swing.JButton();
        Juego3 = new javax.swing.JButton();
        Juego2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PlataformaBBDD = new javax.swing.JLabel();
        GeneroBBDD = new javax.swing.JLabel();
        PrecioBBDD = new javax.swing.JLabel();
        NombreBBDD = new javax.swing.JLabel();
        BotonCancelarCompra = new javax.swing.JButton();
        BotonComprar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ModoBBDD = new javax.swing.JLabel();
        PrecioBBDD1 = new javax.swing.JLabel();
        FechaBBDD = new javax.swing.JLabel();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1925, 1015));

        PanelFiltros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelFiltros.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 690, 70, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Detalles del juego");
        PanelFiltros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 600, -1, -1));
        PanelFiltros.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 830, 160));

        Juego4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.red));
        Juego4.setContentAreaFilled(false);
        Juego4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Juego4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego4ActionPerformed(evt);
            }
        });
        PanelFiltros.add(Juego4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 290, 250, 250));

        Juego1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.red));
        Juego1.setContentAreaFilled(false);
        Juego1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Juego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego1ActionPerformed(evt);
            }
        });
        PanelFiltros.add(Juego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 250, 250));

        Juego3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.red));
        Juego3.setContentAreaFilled(false);
        Juego3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Juego3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego3ActionPerformed(evt);
            }
        });
        PanelFiltros.add(Juego3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 250, 250));

        Juego2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.red));
        Juego2.setContentAreaFilled(false);
        Juego2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Juego2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Juego2ActionPerformed(evt);
            }
        });
        PanelFiltros.add(Juego2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 250, 250));
        PanelFiltros.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 910, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("Resultados encontrados");
        PanelFiltros.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Plataforma:");
        PanelFiltros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Género:");
        PanelFiltros.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 750, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        PanelFiltros.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Precio:");
        PanelFiltros.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 670, -1, -1));

        PlataformaBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PlataformaBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(PlataformaBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 670, 150, 20));

        GeneroBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        GeneroBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(GeneroBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 770, 170, 20));

        PrecioBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PrecioBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(PrecioBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 690, 70, 20));

        NombreBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(NombreBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, 290, 20));

        BotonCancelarCompra.setBackground(java.awt.Color.white);
        BotonCancelarCompra.setForeground(java.awt.Color.red);
        BotonCancelarCompra.setText("Cancelar");
        BotonCancelarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCancelarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCancelarCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCancelarCompraMouseExited(evt);
            }
        });
        BotonCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarCompraActionPerformed(evt);
            }
        });
        PanelFiltros.add(BotonCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 830, 100, 40));

        BotonComprar.setBackground(java.awt.Color.red);
        BotonComprar.setForeground(java.awt.Color.white);
        BotonComprar.setText("Comprar");
        BotonComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonComprarMouseExited(evt);
            }
        });
        BotonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprarActionPerformed(evt);
            }
        });
        PanelFiltros.add(BotonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 830, 100, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Modo de juego:");
        PanelFiltros.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 750, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Fecha de lanzamiento:");
        PanelFiltros.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 750, -1, -1));

        ModoBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ModoBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(ModoBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 750, 160, 20));
        PanelFiltros.add(PrecioBBDD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 960, 200, 20));

        FechaBBDD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FechaBBDD.setForeground(java.awt.Color.red);
        PanelFiltros.add(FechaBBDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 770, 70, 20));
        PanelFiltros.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 1940, 1090));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFiltros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFiltros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarCompraActionPerformed
        // TODO add your handling code here:
        Filtros filtro = new Filtros();
        this.dispose();
    }//GEN-LAST:event_BotonCancelarCompraActionPerformed

    private void BotonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprarActionPerformed
        // TODO add your handling code here:
        nombreJuego = NombreBBDD.getText();
        String generoJuego = GeneroBBDD.getText();
        String plataformaJuego = PlataformaBBDD.getText();
        String modoJuegoJuego = ModoBBDD.getText();
        precioJuego = PrecioBBDD.getText();
        String fechaJuego = FechaBBDD.getText();

        if (NombreBBDD.getText().isEmpty() || GeneroBBDD.getText().isEmpty() || PlataformaBBDD.getText().isEmpty() || ModoBBDD.getText().isEmpty() || PrecioBBDD.getText().isEmpty() || FechaBBDD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un juego");
        } else {
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de querer comprar el juego : " + nombreJuego + "?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == 0) {
                try {
                    Connection cn = conexion.Conexion.conectar();

                    String consulta2 = "SELECT URL FROM videojuegos WHERE Nombre = ?";
                    PreparedStatement enviarConsultas = cn.prepareStatement(consulta2);
                    enviarConsultas.setString(1, nombreJuego);
                    ResultSet resultado = enviarConsultas.executeQuery();

                    if (resultado.next()) {
                        urlJuego = resultado.getString("URL");
                    }

                    String consulta = "INSERT INTO videojuegoSeleccionado (NombreJuego, GeneroJuego, PlataformaJuego, ModoJuego, PrecioJuego, FechaJuego, URL) VALUES (?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement sentencia = cn.prepareStatement(consulta, Statement.RETURN_GENERATED_KEYS);

                    sentencia.setString(1, nombreJuego);
                    sentencia.setString(2, generoJuego);
                    sentencia.setString(3, plataformaJuego);
                    sentencia.setString(4, modoJuegoJuego);
                    sentencia.setString(5, precioJuego);
                    sentencia.setString(6, fechaJuego);
                    sentencia.setString(7, urlJuego);

                    int obtenerId = sentencia.executeUpdate();

                    if (obtenerId > 0) {
                        ResultSet clavePrimaria = sentencia.getGeneratedKeys();
                        if (clavePrimaria.next()) {
                            ID = clavePrimaria.getInt(1);
                        }
                    }
                    cn.close();
                    this.dispose();
                    FinalizarCompra compra = new FinalizarCompra();
                } catch (SQLException e) {
                    e.printStackTrace();
                }

            }

        }
    }//GEN-LAST:event_BotonComprarActionPerformed

    private void Juego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego1ActionPerformed
        // TODO add your handling code here:
        NombreBBDD.setText(Filtros.nombre1);
        GeneroBBDD.setText(Filtros.genero1);
        PlataformaBBDD.setText(Filtros.plataforma1);
        PrecioBBDD.setText(Filtros.precio1);
        ModoBBDD.setText(Filtros.modoJuego1);
        FechaBBDD.setText(Filtros.fecha1);


    }//GEN-LAST:event_Juego1ActionPerformed

    private void Juego2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego2ActionPerformed
        // TODO add your handling code here:
        NombreBBDD.setText(Filtros.nombre2);
        GeneroBBDD.setText(Filtros.genero2);
        PlataformaBBDD.setText(Filtros.plataforma2);
        PrecioBBDD.setText(Filtros.precio2);
        ModoBBDD.setText(Filtros.modoJuego2);
        FechaBBDD.setText(Filtros.fecha2);
    }//GEN-LAST:event_Juego2ActionPerformed

    private void Juego3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego3ActionPerformed
        // TODO add your handling code here:
        NombreBBDD.setText(Filtros.nombre3);
        GeneroBBDD.setText(Filtros.genero3);
        PlataformaBBDD.setText(Filtros.plataforma3);
        PrecioBBDD.setText(Filtros.precio3);
        ModoBBDD.setText(Filtros.modoJuego3);
        FechaBBDD.setText(Filtros.fecha3);
    }//GEN-LAST:event_Juego3ActionPerformed

    private void Juego4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Juego4ActionPerformed
        // TODO add your handling code here:
        NombreBBDD.setText(Filtros.nombre4);
        GeneroBBDD.setText(Filtros.genero4);
        PlataformaBBDD.setText(Filtros.plataforma4);
        PrecioBBDD.setText(Filtros.precio4);
        ModoBBDD.setText(Filtros.modoJuego4);
        FechaBBDD.setText(Filtros.fecha4);
    }//GEN-LAST:event_Juego4ActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText("X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonCancelarCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarCompraMouseEntered
        // TODO add your handling code here:
        BotonCancelarCompra.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonCancelarCompraMouseEntered

    private void BotonCancelarCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarCompraMouseExited
        // TODO add your handling code here:
        BotonCancelarCompra.setBackground(Color.white);
    }//GEN-LAST:event_BotonCancelarCompraMouseExited

    private void BotonComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComprarMouseEntered
        // TODO add your handling code here:
        BotonComprar.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonComprarMouseEntered

    private void BotonComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonComprarMouseExited
        // TODO add your handling code here:
        BotonComprar.setBackground(Color.red);
    }//GEN-LAST:event_BotonComprarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCancelarCompra;
    private javax.swing.JButton BotonComprar;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JLabel FechaBBDD;
    private javax.swing.JLabel GeneroBBDD;
    public static javax.swing.JButton Juego1;
    public static javax.swing.JButton Juego2;
    public static javax.swing.JButton Juego3;
    public static javax.swing.JButton Juego4;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JLabel ModoBBDD;
    private javax.swing.JLabel NombreBBDD;
    private javax.swing.JPanel PanelFiltros;
    private javax.swing.JLabel PlataformaBBDD;
    private javax.swing.JLabel PrecioBBDD;
    private javax.swing.JLabel PrecioBBDD1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    public static int ID;
    public static String nombreJuego;
    public static String precioJuego;
    public static String urlJuego;

}
