/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class TodosDatosCompra extends javax.swing.JFrame {

    /**
     * Creates new form TodosDatosCompra
     */
    public TodosDatosCompra() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        //setLocation(950, 230);
        setResizable(false);
        PanelDatos.setBackground(Color.white);
        PanelMuchosDatos.setBackground(Color.red);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        
        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);
        
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneroJuego = new javax.swing.JLabel();
        PlataformaJuego = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        PanelMuchosDatos = new javax.swing.JPanel();
        ValorFoto = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BancoComprador = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CorreoComprador = new javax.swing.JLabel();
        PrecioJuego = new javax.swing.JLabel();
        NombreComprador = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DNIComprador = new javax.swing.JLabel();
        NombreVideojuego = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        AreaDescripcion = new javax.swing.JTextArea();
        BotonHOME = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1535, 755));

        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelDatos.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 720, 160));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Detalles de la compra");
        PanelDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, -1, -1));

        BotonVolver.setBackground(java.awt.Color.white);
        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Cerrar");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 90, 30));

        PanelMuchosDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ValorFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Cuenta bancaria:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Nombre del comprador:");

        BancoComprador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BancoComprador.setForeground(java.awt.Color.white);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("DNI del comprador:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Correo electrónico:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Descripción:");

        CorreoComprador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CorreoComprador.setForeground(java.awt.Color.white);

        PrecioJuego.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PrecioJuego.setForeground(java.awt.Color.white);

        NombreComprador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreComprador.setForeground(java.awt.Color.white);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Nombre del videojuego:");

        DNIComprador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DNIComprador.setForeground(java.awt.Color.white);

        NombreVideojuego.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NombreVideojuego.setForeground(java.awt.Color.white);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setText("Precio:");

        AreaDescripcion.setBackground(java.awt.Color.red);
        AreaDescripcion.setColumns(20);
        AreaDescripcion.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        AreaDescripcion.setForeground(java.awt.Color.white);
        AreaDescripcion.setRows(5);
        AreaDescripcion.setText("El juego " + NombreVideojuego.getText() + "\npertenece al género " + TodosDatos.generoJuego + "\ny está disponible para " + TodosDatos.plataformaJuego);
        AreaDescripcion.setAutoscrolls(false);
        AreaDescripcion.setBorder(null);
        AreaDescripcion.setCaretColor(java.awt.Color.white);
        AreaDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AreaDescripcion.setDisabledTextColor(java.awt.Color.white);
        AreaDescripcion.setEnabled(false);
        AreaDescripcion.setFocusable(false);
        AreaDescripcion.setSelectedTextColor(java.awt.Color.white);
        AreaDescripcion.setSelectionColor(java.awt.Color.white);

        javax.swing.GroupLayout PanelMuchosDatosLayout = new javax.swing.GroupLayout(PanelMuchosDatos);
        PanelMuchosDatos.setLayout(PanelMuchosDatosLayout);
        PanelMuchosDatosLayout.setHorizontalGroup(
            PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                        .addComponent(NombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NombreVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DNIComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CorreoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(BancoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(PrecioJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AreaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(60, 60, 60)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(ValorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PanelMuchosDatosLayout.setVerticalGroup(
            PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreVideojuego, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                                .addComponent(DNIComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)))
                            .addComponent(PrecioJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CorreoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BancoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(AreaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ValorFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(38, 38, 38))
        );

        PanelDatos.add(PanelMuchosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 730, 290));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(null);
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 510, 40, 50));
        PanelDatos.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -50, 1550, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText(" X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosDatosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosDatosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosDatosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosDatosCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosDatosCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea AreaDescripcion;
    public javax.swing.JLabel BancoComprador;
    private javax.swing.JButton BotonHOME;
    private javax.swing.JButton BotonVolver;
    public javax.swing.JLabel CorreoComprador;
    public javax.swing.JLabel DNIComprador;
    public javax.swing.JLabel GeneroJuego;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JLabel LabelLogo;
    public javax.swing.JLabel NombreComprador;
    public javax.swing.JLabel NombreVideojuego;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelMuchosDatos;
    public javax.swing.JLabel PlataformaJuego;
    public javax.swing.JLabel PrecioJuego;
    public javax.swing.JLabel ValorFoto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
