/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoindividual;

import com.sun.awt.*;
import java.awt.*;
import java.awt.geom.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Hugo
 */
public class TodosDatos extends javax.swing.JFrame {

    /**
     * Creates new form TodosDatos
     */
    public TodosDatos() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        PanelDatos.setBackground(Color.white);
        ImageIcon imagen = new ImageIcon("src/images/gameverse.png");
        LabelLogo.setIcon(imagen);
        PanelMuchosDatos.setBackground(Color.red);
        setIconImage(getIconImage());

        ImageIcon icono1 = new ImageIcon("src/images/Nintendo.png");
        int anchoLabel = LabelFondo.getWidth();
        int altoLabel = LabelFondo.getHeight();
        Image imagenRedimensionada1 = icono1.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
        ImageIcon iconoRedimensionado1 = new ImageIcon(imagenRedimensionada1);
        LabelFondo.setIcon(iconoRedimensionado1);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 300, 300);
        AWTUtilities.setWindowShape(this, forma);

        setVisible(true);
    }

    @Override
    public Image getIconImage() {
        Image miIcono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icono.png"));
        return miIcono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImagen = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CPLabel = new javax.swing.JLabel();
        PuestoLabel = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        ValorApellidos = new javax.swing.JLabel();
        ValorDNI = new javax.swing.JLabel();
        ValorCiudad = new javax.swing.JLabel();
        BotonHOME = new javax.swing.JButton();
        ValorPuesto = new javax.swing.JLabel();
        ValorCP = new javax.swing.JLabel();
        ValorContacto = new javax.swing.JLabel();
        ValorNombre = new javax.swing.JLabel();
        PanelMuchosDatos = new javax.swing.JPanel();
        ValorFoto = new javax.swing.JLabel();
        BotonVerDetallesPedido = new javax.swing.JButton();
        LabelFondo = new javax.swing.JLabel();

        LabelImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1530, 720));

        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelDatos.add(LabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 710, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Todos los datos");
        PanelDatos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        PanelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos:");
        PanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");
        PanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Contacto:");
        PanelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Localidad:");
        PanelDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        CPLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CPLabel.setText("Código postal:");
        PanelDatos.add(CPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        PuestoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PuestoLabel.setText("Puesto:");
        PanelDatos.add(PuestoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        BotonVolver.setBackground(java.awt.Color.white);
        BotonVolver.setForeground(java.awt.Color.red);
        BotonVolver.setText("Volver");
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVolverMouseExited(evt);
            }
        });
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 70, 30));

        ValorApellidos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorApellidos.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 150, 20));

        ValorDNI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorDNI.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 150, 20));

        ValorCiudad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorCiudad.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 160, 20));

        BotonHOME.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        BotonHOME.setForeground(java.awt.Color.white);
        BotonHOME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonHOME.setBorderPainted(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonHOME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHOMEMouseExited(evt);
            }
        });
        BotonHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonHOMEActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 490, 40, 50));

        ValorPuesto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorPuesto.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 160, 20));

        ValorCP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorCP.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 160, 20));

        ValorContacto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorContacto.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 160, 20));

        ValorNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ValorNombre.setForeground(java.awt.Color.white);
        PanelDatos.add(ValorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 150, 20));

        PanelMuchosDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ValorFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelMuchosDatosLayout = new javax.swing.GroupLayout(PanelMuchosDatos);
        PanelMuchosDatos.setLayout(PanelMuchosDatosLayout);
        PanelMuchosDatosLayout.setHorizontalGroup(
            PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMuchosDatosLayout.createSequentialGroup()
                .addContainerGap(419, Short.MAX_VALUE)
                .addComponent(ValorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        PanelMuchosDatosLayout.setVerticalGroup(
            PanelMuchosDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMuchosDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ValorFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PanelDatos.add(PanelMuchosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 660, 250));

        BotonVerDetallesPedido.setBackground(java.awt.Color.red);
        BotonVerDetallesPedido.setForeground(java.awt.Color.white);
        BotonVerDetallesPedido.setText("Ver detalles del pedido");
        BotonVerDetallesPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVerDetallesPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVerDetallesPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVerDetallesPedidoMouseExited(evt);
            }
        });
        BotonVerDetallesPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerDetallesPedidoActionPerformed(evt);
            }
        });
        PanelDatos.add(BotonVerDetallesPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, -1, 30));
        PanelDatos.add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, 1550, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Registro registro = new Registro();
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonVerDetallesPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerDetallesPedidoActionPerformed
        // TODO add your handling code here:

        try {
            Connection cn = conexion.Conexion.conectar();
            if (IniciarSesionCliente.cogerNombreUsu == true || RegistrarCliente.bandera == true) {
                String sql1 = "SELECT * FROM compras AS CO INNER JOIN clientes AS C ON CO.ID_CLIENTES = C.ID WHERE C.ID = ?";
                PreparedStatement enviarConsultas = cn.prepareStatement(sql1);
                if (RegistrarCliente.bandera == true) {
                    enviarConsultas.setInt(1, RegistrarCliente.ID);
                } else {
                    enviarConsultas.setInt(1, IniciarSesionCliente.ID);
                }

                ResultSet resultado = enviarConsultas.executeQuery();

                if (resultado.next()) {

                    nombresCompradores = resultado.getString("NombreComprador");
                    apellidosCompradores = resultado.getString("ApellidosComprador");
                    dniCompradores = resultado.getString("DNIComprador");
                    cuentasBancarias = resultado.getString("CuentaBancaria");
                    correosCompras = resultado.getString("CorreoCompra");
                    IDCompras = resultado.getInt("ID");
                } else {
                    JOptionPane.showMessageDialog(null, "Este cliente no ha realizado aún ninguna compra");
                }

            } else if (IniciarSesionTrabajador.esTrabajador == true || RegistrarTrabajador.bandera == true) {
                String sql1 = "SELECT * FROM compras AS CO INNER JOIN trabajadores AS T ON CO.ID_TRABAJADORES = T.ID WHERE T.ID = ?";
                PreparedStatement enviarConsultas = cn.prepareStatement(sql1);
                if (RegistrarCliente.bandera == true) {
                    enviarConsultas.setInt(1, RegistrarTrabajador.ID);
                } else {
                    enviarConsultas.setInt(1, IniciarSesionTrabajador.ID);
                }

                ResultSet resultado = enviarConsultas.executeQuery();

                if (resultado.next()) {

                    nombresCompradores = resultado.getString("NombreComprador");
                    apellidosCompradores = resultado.getString("ApellidosComprador");
                    dniCompradores = resultado.getString("DNIComprador");
                    cuentasBancarias = resultado.getString("CuentaBancaria");
                    correosCompras = resultado.getString("CorreoCompra");
                    IDCompras = resultado.getInt("ID");

                } else {
                    JOptionPane.showMessageDialog(null, "Este trabajador no ha realizado aún ninguna compra");
                }
            }

            String sql2 = "SELECT * FROM videojuegoSeleccionado AS V INNER JOIN compras AS CO ON V.ID = CO.ID_VIDEOJUEGOS WHERE CO.ID = ?";
            PreparedStatement enviarConsultas2 = cn.prepareStatement(sql2);
            enviarConsultas2.setInt(1, IDCompras);
            ResultSet resultado2 = enviarConsultas2.executeQuery();
            TodosDatosCompra todosDatos = new TodosDatosCompra();

            if (resultado2.next()) {
                nombreJuego = resultado2.getString("NombreJuego");
                generoJuego = resultado2.getString("GeneroJuego");
                plataformaJuego = resultado2.getString("PlataformaJuego");
                modoJuegoJuego = resultado2.getString("ModoJuego");
                precioJuego = resultado2.getString("PrecioJuego");
                fechaJuego = resultado2.getString("FechaJuego");
                urlJuego = resultado2.getString("URL");

                icono = new ImageIcon("src/images/Juegos/" + urlJuego);
                int anchoLabel = todosDatos.ValorFoto.getWidth();
                int altoLabel = todosDatos.ValorFoto.getHeight();
                Image imagenRedimensionada = icono.getImage().getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);
                ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);

                todosDatos.setVisible(true);

                todosDatos.NombreComprador.setText(nombresCompradores + " " + apellidosCompradores);
                todosDatos.DNIComprador.setText(dniCompradores);
                todosDatos.BancoComprador.setText(cuentasBancarias.substring(0, 6) + "...");
                todosDatos.CorreoComprador.setText(correosCompras);
                todosDatos.NombreVideojuego.setText(nombreJuego);
                todosDatos.PrecioJuego.setText(precioJuego);
                todosDatos.PlataformaJuego.setText(plataformaJuego);
                todosDatos.GeneroJuego.setText(generoJuego);
                todosDatos.ValorFoto.setIcon(iconoRedimensionado);
                todosDatos.AreaDescripcion.setText("El juego " + nombreJuego + "\npertenece al género\n" + generoJuego + " y está\ndisponible para " + plataformaJuego);
            }

            cn.close();
        } catch (SQLException e) {
            System.err.println("Error al obtener los datos" + e.getMessage());
        }

    }//GEN-LAST:event_BotonVerDetallesPedidoActionPerformed

    private void BotonHOMEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseEntered
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setForeground(Color.red);
        BotonHOME.setText(" X");
    }//GEN-LAST:event_BotonHOMEMouseEntered

    private void BotonHOMEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHOMEMouseExited
        // TODO add your handling code here:
        BotonHOME.setOpaque(false);
        BotonHOME.setContentAreaFilled(false);
        BotonHOME.setText("");
    }//GEN-LAST:event_BotonHOMEMouseExited

    private void BotonHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonHOMEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonHOMEActionPerformed

    private void BotonVerDetallesPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerDetallesPedidoMouseEntered
        // TODO add your handling code here:
        BotonVerDetallesPedido.setBackground(new Color(255, 102, 102));
    }//GEN-LAST:event_BotonVerDetallesPedidoMouseEntered

    private void BotonVerDetallesPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerDetallesPedidoMouseExited
        // TODO add your handling code here:
        BotonVerDetallesPedido.setBackground(Color.red);
    }//GEN-LAST:event_BotonVerDetallesPedidoMouseExited

    private void BotonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseEntered
        // TODO add your handling code here:
        BotonVolver.setBackground(new Color(180, 180, 180));
    }//GEN-LAST:event_BotonVolverMouseEntered

    private void BotonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVolverMouseExited
        // TODO add your handling code here:
        BotonVolver.setBackground(Color.white);
    }//GEN-LAST:event_BotonVolverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHOME;
    public javax.swing.JButton BotonVerDetallesPedido;
    private javax.swing.JButton BotonVolver;
    public static javax.swing.JLabel CPLabel;
    private javax.swing.JLabel LabelFondo;
    public static javax.swing.JLabel LabelImagen;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelMuchosDatos;
    public static javax.swing.JLabel PuestoLabel;
    public static javax.swing.JLabel ValorApellidos;
    public static javax.swing.JLabel ValorCP;
    public static javax.swing.JLabel ValorCiudad;
    public static javax.swing.JLabel ValorContacto;
    public static javax.swing.JLabel ValorDNI;
    public static javax.swing.JLabel ValorFoto;
    public static javax.swing.JLabel ValorNombre;
    public static javax.swing.JLabel ValorPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
    ImageIcon vacio;
    public static int IDCompras;
    ImageIcon icono;
    public static String nombre;
    public static String apellidos;
    public static String DNI;
    public static String contacto;
    public static String pais;
    public static String cp;
    public static String ciudad;
    public static String urlImage;
    public static ImageIcon iconoRedimensionado;

    public static String nombreJuego;
    public static String generoJuego;
    public static String plataformaJuego;
    public static String modoJuegoJuego;
    public static String precioJuego;
    public static String fechaJuego;
    public static String urlJuego;

    public static String nombresCompradores;
    public static String apellidosCompradores;
    public static String dniCompradores;
    public static String cuentasBancarias;
    public static String correosCompras;

}
